### PR TITLE
feat: add chisel manifest to images

### PR DESCRIPTION
**Pull request by cjdcordeiro**
Add the Chisel manifest to all images.

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
1.0.0 isn't available in rockcraft yet. We need https://github.com/canonical/rockcraft/pull/464 and then we can resume this PR

**Comment by cjdcordeiro** [comment]
@rebornplusplus ready for review

**Comment by cjdcordeiro** [comment]
We could. Doesn't feel like a test that belongs here though. The behaviour already looks assertive enough in the sense that if `base-files_chisel` is not supported, it will fail (which was the case of the previous checks in this PR).

Also, checking for a specific path for the manifest is not future-proof as the `base-files_chisel` may not be the only one delivering the manifest.

**Review by rebornplusplus — APPROVED** [review]
> We could. Doesn't feel like a test that belongs here though. The behaviour already looks assertive enough in the sense that if `base-files_chisel` is not supported, it will fail (which was the case of the previous checks in this PR).
> 
> Also, checking for a specific path for the manifest is not future-proof as the `base-files_chisel` may not be the only one delivering the manifest.

Fair enough.

**Pull request merged**
